// Code generated by entc, DO NOT EDIT.

package applicationgroup

import (
	"entgo.io/ent/dialect/sql"
	"github.com/NpoolPlatform/application-management/pkg/db/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// AppID applies equality check predicate on the "app_id" field. It's identical to AppIDEQ.
func AppID(v string) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldAppID), v))
	})
}

// GroupName applies equality check predicate on the "group_name" field. It's identical to GroupNameEQ.
func GroupName(v string) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldGroupName), v))
	})
}

// GroupLogo applies equality check predicate on the "group_logo" field. It's identical to GroupLogoEQ.
func GroupLogo(v string) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldGroupLogo), v))
	})
}

// GroupOwner applies equality check predicate on the "group_owner" field. It's identical to GroupOwnerEQ.
func GroupOwner(v uuid.UUID) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldGroupOwner), v))
	})
}

// Annotation applies equality check predicate on the "annotation" field. It's identical to AnnotationEQ.
func Annotation(v string) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldAnnotation), v))
	})
}

// CreateAt applies equality check predicate on the "create_at" field. It's identical to CreateAtEQ.
func CreateAt(v uint32) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreateAt), v))
	})
}

// UpdateAt applies equality check predicate on the "update_at" field. It's identical to UpdateAtEQ.
func UpdateAt(v uint32) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdateAt), v))
	})
}

// DeleteAt applies equality check predicate on the "delete_at" field. It's identical to DeleteAtEQ.
func DeleteAt(v uint32) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDeleteAt), v))
	})
}

// AppIDEQ applies the EQ predicate on the "app_id" field.
func AppIDEQ(v string) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldAppID), v))
	})
}

// AppIDNEQ applies the NEQ predicate on the "app_id" field.
func AppIDNEQ(v string) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldAppID), v))
	})
}

// AppIDIn applies the In predicate on the "app_id" field.
func AppIDIn(vs ...string) predicate.ApplicationGroup {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldAppID), v...))
	})
}

// AppIDNotIn applies the NotIn predicate on the "app_id" field.
func AppIDNotIn(vs ...string) predicate.ApplicationGroup {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldAppID), v...))
	})
}

// AppIDGT applies the GT predicate on the "app_id" field.
func AppIDGT(v string) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldAppID), v))
	})
}

// AppIDGTE applies the GTE predicate on the "app_id" field.
func AppIDGTE(v string) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldAppID), v))
	})
}

// AppIDLT applies the LT predicate on the "app_id" field.
func AppIDLT(v string) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldAppID), v))
	})
}

// AppIDLTE applies the LTE predicate on the "app_id" field.
func AppIDLTE(v string) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldAppID), v))
	})
}

// AppIDContains applies the Contains predicate on the "app_id" field.
func AppIDContains(v string) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldAppID), v))
	})
}

// AppIDHasPrefix applies the HasPrefix predicate on the "app_id" field.
func AppIDHasPrefix(v string) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldAppID), v))
	})
}

// AppIDHasSuffix applies the HasSuffix predicate on the "app_id" field.
func AppIDHasSuffix(v string) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldAppID), v))
	})
}

// AppIDEqualFold applies the EqualFold predicate on the "app_id" field.
func AppIDEqualFold(v string) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldAppID), v))
	})
}

// AppIDContainsFold applies the ContainsFold predicate on the "app_id" field.
func AppIDContainsFold(v string) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldAppID), v))
	})
}

// GroupNameEQ applies the EQ predicate on the "group_name" field.
func GroupNameEQ(v string) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldGroupName), v))
	})
}

// GroupNameNEQ applies the NEQ predicate on the "group_name" field.
func GroupNameNEQ(v string) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldGroupName), v))
	})
}

// GroupNameIn applies the In predicate on the "group_name" field.
func GroupNameIn(vs ...string) predicate.ApplicationGroup {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldGroupName), v...))
	})
}

// GroupNameNotIn applies the NotIn predicate on the "group_name" field.
func GroupNameNotIn(vs ...string) predicate.ApplicationGroup {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldGroupName), v...))
	})
}

// GroupNameGT applies the GT predicate on the "group_name" field.
func GroupNameGT(v string) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldGroupName), v))
	})
}

// GroupNameGTE applies the GTE predicate on the "group_name" field.
func GroupNameGTE(v string) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldGroupName), v))
	})
}

// GroupNameLT applies the LT predicate on the "group_name" field.
func GroupNameLT(v string) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldGroupName), v))
	})
}

// GroupNameLTE applies the LTE predicate on the "group_name" field.
func GroupNameLTE(v string) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldGroupName), v))
	})
}

// GroupNameContains applies the Contains predicate on the "group_name" field.
func GroupNameContains(v string) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldGroupName), v))
	})
}

// GroupNameHasPrefix applies the HasPrefix predicate on the "group_name" field.
func GroupNameHasPrefix(v string) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldGroupName), v))
	})
}

// GroupNameHasSuffix applies the HasSuffix predicate on the "group_name" field.
func GroupNameHasSuffix(v string) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldGroupName), v))
	})
}

// GroupNameEqualFold applies the EqualFold predicate on the "group_name" field.
func GroupNameEqualFold(v string) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldGroupName), v))
	})
}

// GroupNameContainsFold applies the ContainsFold predicate on the "group_name" field.
func GroupNameContainsFold(v string) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldGroupName), v))
	})
}

// GroupLogoEQ applies the EQ predicate on the "group_logo" field.
func GroupLogoEQ(v string) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldGroupLogo), v))
	})
}

// GroupLogoNEQ applies the NEQ predicate on the "group_logo" field.
func GroupLogoNEQ(v string) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldGroupLogo), v))
	})
}

// GroupLogoIn applies the In predicate on the "group_logo" field.
func GroupLogoIn(vs ...string) predicate.ApplicationGroup {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldGroupLogo), v...))
	})
}

// GroupLogoNotIn applies the NotIn predicate on the "group_logo" field.
func GroupLogoNotIn(vs ...string) predicate.ApplicationGroup {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldGroupLogo), v...))
	})
}

// GroupLogoGT applies the GT predicate on the "group_logo" field.
func GroupLogoGT(v string) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldGroupLogo), v))
	})
}

// GroupLogoGTE applies the GTE predicate on the "group_logo" field.
func GroupLogoGTE(v string) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldGroupLogo), v))
	})
}

// GroupLogoLT applies the LT predicate on the "group_logo" field.
func GroupLogoLT(v string) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldGroupLogo), v))
	})
}

// GroupLogoLTE applies the LTE predicate on the "group_logo" field.
func GroupLogoLTE(v string) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldGroupLogo), v))
	})
}

// GroupLogoContains applies the Contains predicate on the "group_logo" field.
func GroupLogoContains(v string) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldGroupLogo), v))
	})
}

// GroupLogoHasPrefix applies the HasPrefix predicate on the "group_logo" field.
func GroupLogoHasPrefix(v string) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldGroupLogo), v))
	})
}

// GroupLogoHasSuffix applies the HasSuffix predicate on the "group_logo" field.
func GroupLogoHasSuffix(v string) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldGroupLogo), v))
	})
}

// GroupLogoIsNil applies the IsNil predicate on the "group_logo" field.
func GroupLogoIsNil() predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldGroupLogo)))
	})
}

// GroupLogoNotNil applies the NotNil predicate on the "group_logo" field.
func GroupLogoNotNil() predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldGroupLogo)))
	})
}

// GroupLogoEqualFold applies the EqualFold predicate on the "group_logo" field.
func GroupLogoEqualFold(v string) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldGroupLogo), v))
	})
}

// GroupLogoContainsFold applies the ContainsFold predicate on the "group_logo" field.
func GroupLogoContainsFold(v string) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldGroupLogo), v))
	})
}

// GroupOwnerEQ applies the EQ predicate on the "group_owner" field.
func GroupOwnerEQ(v uuid.UUID) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldGroupOwner), v))
	})
}

// GroupOwnerNEQ applies the NEQ predicate on the "group_owner" field.
func GroupOwnerNEQ(v uuid.UUID) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldGroupOwner), v))
	})
}

// GroupOwnerIn applies the In predicate on the "group_owner" field.
func GroupOwnerIn(vs ...uuid.UUID) predicate.ApplicationGroup {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldGroupOwner), v...))
	})
}

// GroupOwnerNotIn applies the NotIn predicate on the "group_owner" field.
func GroupOwnerNotIn(vs ...uuid.UUID) predicate.ApplicationGroup {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldGroupOwner), v...))
	})
}

// GroupOwnerGT applies the GT predicate on the "group_owner" field.
func GroupOwnerGT(v uuid.UUID) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldGroupOwner), v))
	})
}

// GroupOwnerGTE applies the GTE predicate on the "group_owner" field.
func GroupOwnerGTE(v uuid.UUID) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldGroupOwner), v))
	})
}

// GroupOwnerLT applies the LT predicate on the "group_owner" field.
func GroupOwnerLT(v uuid.UUID) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldGroupOwner), v))
	})
}

// GroupOwnerLTE applies the LTE predicate on the "group_owner" field.
func GroupOwnerLTE(v uuid.UUID) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldGroupOwner), v))
	})
}

// AnnotationEQ applies the EQ predicate on the "annotation" field.
func AnnotationEQ(v string) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldAnnotation), v))
	})
}

// AnnotationNEQ applies the NEQ predicate on the "annotation" field.
func AnnotationNEQ(v string) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldAnnotation), v))
	})
}

// AnnotationIn applies the In predicate on the "annotation" field.
func AnnotationIn(vs ...string) predicate.ApplicationGroup {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldAnnotation), v...))
	})
}

// AnnotationNotIn applies the NotIn predicate on the "annotation" field.
func AnnotationNotIn(vs ...string) predicate.ApplicationGroup {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldAnnotation), v...))
	})
}

// AnnotationGT applies the GT predicate on the "annotation" field.
func AnnotationGT(v string) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldAnnotation), v))
	})
}

// AnnotationGTE applies the GTE predicate on the "annotation" field.
func AnnotationGTE(v string) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldAnnotation), v))
	})
}

// AnnotationLT applies the LT predicate on the "annotation" field.
func AnnotationLT(v string) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldAnnotation), v))
	})
}

// AnnotationLTE applies the LTE predicate on the "annotation" field.
func AnnotationLTE(v string) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldAnnotation), v))
	})
}

// AnnotationContains applies the Contains predicate on the "annotation" field.
func AnnotationContains(v string) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldAnnotation), v))
	})
}

// AnnotationHasPrefix applies the HasPrefix predicate on the "annotation" field.
func AnnotationHasPrefix(v string) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldAnnotation), v))
	})
}

// AnnotationHasSuffix applies the HasSuffix predicate on the "annotation" field.
func AnnotationHasSuffix(v string) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldAnnotation), v))
	})
}

// AnnotationIsNil applies the IsNil predicate on the "annotation" field.
func AnnotationIsNil() predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldAnnotation)))
	})
}

// AnnotationNotNil applies the NotNil predicate on the "annotation" field.
func AnnotationNotNil() predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldAnnotation)))
	})
}

// AnnotationEqualFold applies the EqualFold predicate on the "annotation" field.
func AnnotationEqualFold(v string) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldAnnotation), v))
	})
}

// AnnotationContainsFold applies the ContainsFold predicate on the "annotation" field.
func AnnotationContainsFold(v string) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldAnnotation), v))
	})
}

// CreateAtEQ applies the EQ predicate on the "create_at" field.
func CreateAtEQ(v uint32) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreateAt), v))
	})
}

// CreateAtNEQ applies the NEQ predicate on the "create_at" field.
func CreateAtNEQ(v uint32) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCreateAt), v))
	})
}

// CreateAtIn applies the In predicate on the "create_at" field.
func CreateAtIn(vs ...uint32) predicate.ApplicationGroup {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldCreateAt), v...))
	})
}

// CreateAtNotIn applies the NotIn predicate on the "create_at" field.
func CreateAtNotIn(vs ...uint32) predicate.ApplicationGroup {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldCreateAt), v...))
	})
}

// CreateAtGT applies the GT predicate on the "create_at" field.
func CreateAtGT(v uint32) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCreateAt), v))
	})
}

// CreateAtGTE applies the GTE predicate on the "create_at" field.
func CreateAtGTE(v uint32) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCreateAt), v))
	})
}

// CreateAtLT applies the LT predicate on the "create_at" field.
func CreateAtLT(v uint32) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCreateAt), v))
	})
}

// CreateAtLTE applies the LTE predicate on the "create_at" field.
func CreateAtLTE(v uint32) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCreateAt), v))
	})
}

// UpdateAtEQ applies the EQ predicate on the "update_at" field.
func UpdateAtEQ(v uint32) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdateAt), v))
	})
}

// UpdateAtNEQ applies the NEQ predicate on the "update_at" field.
func UpdateAtNEQ(v uint32) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldUpdateAt), v))
	})
}

// UpdateAtIn applies the In predicate on the "update_at" field.
func UpdateAtIn(vs ...uint32) predicate.ApplicationGroup {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldUpdateAt), v...))
	})
}

// UpdateAtNotIn applies the NotIn predicate on the "update_at" field.
func UpdateAtNotIn(vs ...uint32) predicate.ApplicationGroup {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldUpdateAt), v...))
	})
}

// UpdateAtGT applies the GT predicate on the "update_at" field.
func UpdateAtGT(v uint32) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldUpdateAt), v))
	})
}

// UpdateAtGTE applies the GTE predicate on the "update_at" field.
func UpdateAtGTE(v uint32) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldUpdateAt), v))
	})
}

// UpdateAtLT applies the LT predicate on the "update_at" field.
func UpdateAtLT(v uint32) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldUpdateAt), v))
	})
}

// UpdateAtLTE applies the LTE predicate on the "update_at" field.
func UpdateAtLTE(v uint32) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldUpdateAt), v))
	})
}

// DeleteAtEQ applies the EQ predicate on the "delete_at" field.
func DeleteAtEQ(v uint32) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDeleteAt), v))
	})
}

// DeleteAtNEQ applies the NEQ predicate on the "delete_at" field.
func DeleteAtNEQ(v uint32) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldDeleteAt), v))
	})
}

// DeleteAtIn applies the In predicate on the "delete_at" field.
func DeleteAtIn(vs ...uint32) predicate.ApplicationGroup {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldDeleteAt), v...))
	})
}

// DeleteAtNotIn applies the NotIn predicate on the "delete_at" field.
func DeleteAtNotIn(vs ...uint32) predicate.ApplicationGroup {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldDeleteAt), v...))
	})
}

// DeleteAtGT applies the GT predicate on the "delete_at" field.
func DeleteAtGT(v uint32) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldDeleteAt), v))
	})
}

// DeleteAtGTE applies the GTE predicate on the "delete_at" field.
func DeleteAtGTE(v uint32) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldDeleteAt), v))
	})
}

// DeleteAtLT applies the LT predicate on the "delete_at" field.
func DeleteAtLT(v uint32) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldDeleteAt), v))
	})
}

// DeleteAtLTE applies the LTE predicate on the "delete_at" field.
func DeleteAtLTE(v uint32) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldDeleteAt), v))
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ApplicationGroup) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ApplicationGroup) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ApplicationGroup) predicate.ApplicationGroup {
	return predicate.ApplicationGroup(func(s *sql.Selector) {
		p(s.Not())
	})
}
