// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/application-management/pkg/db/ent/applicationuser"
	"github.com/NpoolPlatform/application-management/pkg/db/ent/predicate"
)

// ApplicationUserDelete is the builder for deleting a ApplicationUser entity.
type ApplicationUserDelete struct {
	config
	hooks    []Hook
	mutation *ApplicationUserMutation
}

// Where appends a list predicates to the ApplicationUserDelete builder.
func (aud *ApplicationUserDelete) Where(ps ...predicate.ApplicationUser) *ApplicationUserDelete {
	aud.mutation.Where(ps...)
	return aud
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (aud *ApplicationUserDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(aud.hooks) == 0 {
		affected, err = aud.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ApplicationUserMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			aud.mutation = mutation
			affected, err = aud.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(aud.hooks) - 1; i >= 0; i-- {
			if aud.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = aud.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, aud.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (aud *ApplicationUserDelete) ExecX(ctx context.Context) int {
	n, err := aud.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (aud *ApplicationUserDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: applicationuser.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: applicationuser.FieldID,
			},
		},
	}
	if ps := aud.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, aud.driver, _spec)
}

// ApplicationUserDeleteOne is the builder for deleting a single ApplicationUser entity.
type ApplicationUserDeleteOne struct {
	aud *ApplicationUserDelete
}

// Exec executes the deletion query.
func (audo *ApplicationUserDeleteOne) Exec(ctx context.Context) error {
	n, err := audo.aud.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{applicationuser.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (audo *ApplicationUserDeleteOne) ExecX(ctx context.Context) {
	audo.aud.ExecX(ctx)
}
