// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/application-management/pkg/db/ent/applicationgroupuser"
	"github.com/google/uuid"
)

// ApplicationGroupUserCreate is the builder for creating a ApplicationGroupUser entity.
type ApplicationGroupUserCreate struct {
	config
	mutation *ApplicationGroupUserMutation
	hooks    []Hook
}

// SetGroupID sets the "group_id" field.
func (aguc *ApplicationGroupUserCreate) SetGroupID(u uuid.UUID) *ApplicationGroupUserCreate {
	aguc.mutation.SetGroupID(u)
	return aguc
}

// SetAppID sets the "app_id" field.
func (aguc *ApplicationGroupUserCreate) SetAppID(u uuid.UUID) *ApplicationGroupUserCreate {
	aguc.mutation.SetAppID(u)
	return aguc
}

// SetUserID sets the "user_id" field.
func (aguc *ApplicationGroupUserCreate) SetUserID(u uuid.UUID) *ApplicationGroupUserCreate {
	aguc.mutation.SetUserID(u)
	return aguc
}

// SetAnnotation sets the "annotation" field.
func (aguc *ApplicationGroupUserCreate) SetAnnotation(s string) *ApplicationGroupUserCreate {
	aguc.mutation.SetAnnotation(s)
	return aguc
}

// SetNillableAnnotation sets the "annotation" field if the given value is not nil.
func (aguc *ApplicationGroupUserCreate) SetNillableAnnotation(s *string) *ApplicationGroupUserCreate {
	if s != nil {
		aguc.SetAnnotation(*s)
	}
	return aguc
}

// SetCreateAt sets the "create_at" field.
func (aguc *ApplicationGroupUserCreate) SetCreateAt(u uint32) *ApplicationGroupUserCreate {
	aguc.mutation.SetCreateAt(u)
	return aguc
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (aguc *ApplicationGroupUserCreate) SetNillableCreateAt(u *uint32) *ApplicationGroupUserCreate {
	if u != nil {
		aguc.SetCreateAt(*u)
	}
	return aguc
}

// SetDeleteAt sets the "delete_at" field.
func (aguc *ApplicationGroupUserCreate) SetDeleteAt(u uint32) *ApplicationGroupUserCreate {
	aguc.mutation.SetDeleteAt(u)
	return aguc
}

// SetNillableDeleteAt sets the "delete_at" field if the given value is not nil.
func (aguc *ApplicationGroupUserCreate) SetNillableDeleteAt(u *uint32) *ApplicationGroupUserCreate {
	if u != nil {
		aguc.SetDeleteAt(*u)
	}
	return aguc
}

// SetID sets the "id" field.
func (aguc *ApplicationGroupUserCreate) SetID(u uuid.UUID) *ApplicationGroupUserCreate {
	aguc.mutation.SetID(u)
	return aguc
}

// Mutation returns the ApplicationGroupUserMutation object of the builder.
func (aguc *ApplicationGroupUserCreate) Mutation() *ApplicationGroupUserMutation {
	return aguc.mutation
}

// Save creates the ApplicationGroupUser in the database.
func (aguc *ApplicationGroupUserCreate) Save(ctx context.Context) (*ApplicationGroupUser, error) {
	var (
		err  error
		node *ApplicationGroupUser
	)
	aguc.defaults()
	if len(aguc.hooks) == 0 {
		if err = aguc.check(); err != nil {
			return nil, err
		}
		node, err = aguc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ApplicationGroupUserMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = aguc.check(); err != nil {
				return nil, err
			}
			aguc.mutation = mutation
			if node, err = aguc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(aguc.hooks) - 1; i >= 0; i-- {
			if aguc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = aguc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, aguc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (aguc *ApplicationGroupUserCreate) SaveX(ctx context.Context) *ApplicationGroupUser {
	v, err := aguc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (aguc *ApplicationGroupUserCreate) Exec(ctx context.Context) error {
	_, err := aguc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aguc *ApplicationGroupUserCreate) ExecX(ctx context.Context) {
	if err := aguc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (aguc *ApplicationGroupUserCreate) defaults() {
	if _, ok := aguc.mutation.CreateAt(); !ok {
		v := applicationgroupuser.DefaultCreateAt()
		aguc.mutation.SetCreateAt(v)
	}
	if _, ok := aguc.mutation.DeleteAt(); !ok {
		v := applicationgroupuser.DefaultDeleteAt()
		aguc.mutation.SetDeleteAt(v)
	}
	if _, ok := aguc.mutation.ID(); !ok {
		v := applicationgroupuser.DefaultID()
		aguc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (aguc *ApplicationGroupUserCreate) check() error {
	if _, ok := aguc.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "group_id"`)}
	}
	if _, ok := aguc.mutation.AppID(); !ok {
		return &ValidationError{Name: "app_id", err: errors.New(`ent: missing required field "app_id"`)}
	}
	if _, ok := aguc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "user_id"`)}
	}
	if _, ok := aguc.mutation.CreateAt(); !ok {
		return &ValidationError{Name: "create_at", err: errors.New(`ent: missing required field "create_at"`)}
	}
	if _, ok := aguc.mutation.DeleteAt(); !ok {
		return &ValidationError{Name: "delete_at", err: errors.New(`ent: missing required field "delete_at"`)}
	}
	return nil
}

func (aguc *ApplicationGroupUserCreate) sqlSave(ctx context.Context) (*ApplicationGroupUser, error) {
	_node, _spec := aguc.createSpec()
	if err := sqlgraph.CreateNode(ctx, aguc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		_node.ID = _spec.ID.Value.(uuid.UUID)
	}
	return _node, nil
}

func (aguc *ApplicationGroupUserCreate) createSpec() (*ApplicationGroupUser, *sqlgraph.CreateSpec) {
	var (
		_node = &ApplicationGroupUser{config: aguc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: applicationgroupuser.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: applicationgroupuser.FieldID,
			},
		}
	)
	if id, ok := aguc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := aguc.mutation.GroupID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: applicationgroupuser.FieldGroupID,
		})
		_node.GroupID = value
	}
	if value, ok := aguc.mutation.AppID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: applicationgroupuser.FieldAppID,
		})
		_node.AppID = value
	}
	if value, ok := aguc.mutation.UserID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: applicationgroupuser.FieldUserID,
		})
		_node.UserID = value
	}
	if value, ok := aguc.mutation.Annotation(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: applicationgroupuser.FieldAnnotation,
		})
		_node.Annotation = value
	}
	if value, ok := aguc.mutation.CreateAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: applicationgroupuser.FieldCreateAt,
		})
		_node.CreateAt = value
	}
	if value, ok := aguc.mutation.DeleteAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: applicationgroupuser.FieldDeleteAt,
		})
		_node.DeleteAt = value
	}
	return _node, _spec
}

// ApplicationGroupUserCreateBulk is the builder for creating many ApplicationGroupUser entities in bulk.
type ApplicationGroupUserCreateBulk struct {
	config
	builders []*ApplicationGroupUserCreate
}

// Save creates the ApplicationGroupUser entities in the database.
func (agucb *ApplicationGroupUserCreateBulk) Save(ctx context.Context) ([]*ApplicationGroupUser, error) {
	specs := make([]*sqlgraph.CreateSpec, len(agucb.builders))
	nodes := make([]*ApplicationGroupUser, len(agucb.builders))
	mutators := make([]Mutator, len(agucb.builders))
	for i := range agucb.builders {
		func(i int, root context.Context) {
			builder := agucb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ApplicationGroupUserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, agucb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, agucb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, agucb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (agucb *ApplicationGroupUserCreateBulk) SaveX(ctx context.Context) []*ApplicationGroupUser {
	v, err := agucb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (agucb *ApplicationGroupUserCreateBulk) Exec(ctx context.Context) error {
	_, err := agucb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (agucb *ApplicationGroupUserCreateBulk) ExecX(ctx context.Context) {
	if err := agucb.Exec(ctx); err != nil {
		panic(err)
	}
}
