// Code generated by entc, DO NOT EDIT.

package application

import (
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the application type in the database.
	Label = "application"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldApplicationName holds the string denoting the application_name field in the database.
	FieldApplicationName = "application_name"
	// FieldApplicationOwner holds the string denoting the application_owner field in the database.
	FieldApplicationOwner = "application_owner"
	// FieldHomepageURL holds the string denoting the homepage_url field in the database.
	FieldHomepageURL = "homepage_url"
	// FieldRedirectURL holds the string denoting the redirect_url field in the database.
	FieldRedirectURL = "redirect_url"
	// FieldClientSecret holds the string denoting the client_secret field in the database.
	FieldClientSecret = "client_secret"
	// FieldApplicationLogo holds the string denoting the application_logo field in the database.
	FieldApplicationLogo = "application_logo"
	// FieldSmsLogin holds the string denoting the sms_login field in the database.
	FieldSmsLogin = "sms_login"
	// FieldGoogleRecaptcha holds the string denoting the google_recaptcha field in the database.
	FieldGoogleRecaptcha = "google_recaptcha"
	// FieldInvitationCodeMust holds the string denoting the invitation_code_must field in the database.
	FieldInvitationCodeMust = "invitation_code_must"
	// FieldCreateAt holds the string denoting the create_at field in the database.
	FieldCreateAt = "create_at"
	// FieldUpdateAt holds the string denoting the update_at field in the database.
	FieldUpdateAt = "update_at"
	// FieldDeleteAt holds the string denoting the delete_at field in the database.
	FieldDeleteAt = "delete_at"
	// Table holds the table name of the application in the database.
	Table = "applications"
)

// Columns holds all SQL columns for application fields.
var Columns = []string{
	FieldID,
	FieldApplicationName,
	FieldApplicationOwner,
	FieldHomepageURL,
	FieldRedirectURL,
	FieldClientSecret,
	FieldApplicationLogo,
	FieldSmsLogin,
	FieldGoogleRecaptcha,
	FieldInvitationCodeMust,
	FieldCreateAt,
	FieldUpdateAt,
	FieldDeleteAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultClientSecret holds the default value on creation for the "client_secret" field.
	DefaultClientSecret func() string
	// DefaultSmsLogin holds the default value on creation for the "sms_login" field.
	DefaultSmsLogin bool
	// DefaultGoogleRecaptcha holds the default value on creation for the "google_recaptcha" field.
	DefaultGoogleRecaptcha bool
	// DefaultInvitationCodeMust holds the default value on creation for the "invitation_code_must" field.
	DefaultInvitationCodeMust bool
	// DefaultCreateAt holds the default value on creation for the "create_at" field.
	DefaultCreateAt func() uint32
	// DefaultUpdateAt holds the default value on creation for the "update_at" field.
	DefaultUpdateAt func() uint32
	// UpdateDefaultUpdateAt holds the default value on update for the "update_at" field.
	UpdateDefaultUpdateAt func() uint32
	// DefaultDeleteAt holds the default value on creation for the "delete_at" field.
	DefaultDeleteAt func() uint32
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
