apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-management
  namespace: kube-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: application-management
  template:
    metadata:
      labels:
        app: application-management
    spec:
      containers:
      - name: application-management
        image: entropypool/application-management:latest
        imagePullPolicy: Always
        env:
        - name: ENV_ENVIRONMENT_TARGET
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.target
        - name: ENV_CONSUL_HOST
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.consul_host
        - name: ENV_CONSUL_PORT
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.consul_port
        - name: ENV_CLUSTER_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

---
apiVersion: v1
kind: Service
metadata:
  name: application-management
  namespace: kube-system
spec:
  ports:
  - name: api
    port: 50080
    targetPort: 50080
  - name: grpc
    port: 50081
    targetPort: 50081
  - name: prometheus
    port: 50082
    targetPort: 50082
  selector:
    app: application-management