// Code generated by entc, DO NOT EDIT.

package applicationuser

import (
	"entgo.io/ent/dialect/sql"
	"github.com/NpoolPlatform/application-management/pkg/db/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// AppID applies equality check predicate on the "app_id" field. It's identical to AppIDEQ.
func AppID(v uuid.UUID) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldAppID), v))
	})
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUserID), v))
	})
}

// Original applies equality check predicate on the "original" field. It's identical to OriginalEQ.
func Original(v bool) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldOriginal), v))
	})
}

// KycVerify applies equality check predicate on the "kyc_verify" field. It's identical to KycVerifyEQ.
func KycVerify(v bool) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldKycVerify), v))
	})
}

// GaVerify applies equality check predicate on the "ga_verify" field. It's identical to GaVerifyEQ.
func GaVerify(v bool) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldGaVerify), v))
	})
}

// GaLogin applies equality check predicate on the "ga_login" field. It's identical to GaLoginEQ.
func GaLogin(v bool) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldGaLogin), v))
	})
}

// SmsLogin applies equality check predicate on the "sms_login" field. It's identical to SmsLoginEQ.
func SmsLogin(v bool) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSmsLogin), v))
	})
}

// LoginNumber applies equality check predicate on the "Login_number" field. It's identical to LoginNumberEQ.
func LoginNumber(v uint32) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldLoginNumber), v))
	})
}

// CreateAt applies equality check predicate on the "create_at" field. It's identical to CreateAtEQ.
func CreateAt(v uint32) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreateAt), v))
	})
}

// DeleteAt applies equality check predicate on the "delete_at" field. It's identical to DeleteAtEQ.
func DeleteAt(v uint32) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDeleteAt), v))
	})
}

// AppIDEQ applies the EQ predicate on the "app_id" field.
func AppIDEQ(v uuid.UUID) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldAppID), v))
	})
}

// AppIDNEQ applies the NEQ predicate on the "app_id" field.
func AppIDNEQ(v uuid.UUID) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldAppID), v))
	})
}

// AppIDIn applies the In predicate on the "app_id" field.
func AppIDIn(vs ...uuid.UUID) predicate.ApplicationUser {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ApplicationUser(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldAppID), v...))
	})
}

// AppIDNotIn applies the NotIn predicate on the "app_id" field.
func AppIDNotIn(vs ...uuid.UUID) predicate.ApplicationUser {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ApplicationUser(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldAppID), v...))
	})
}

// AppIDGT applies the GT predicate on the "app_id" field.
func AppIDGT(v uuid.UUID) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldAppID), v))
	})
}

// AppIDGTE applies the GTE predicate on the "app_id" field.
func AppIDGTE(v uuid.UUID) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldAppID), v))
	})
}

// AppIDLT applies the LT predicate on the "app_id" field.
func AppIDLT(v uuid.UUID) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldAppID), v))
	})
}

// AppIDLTE applies the LTE predicate on the "app_id" field.
func AppIDLTE(v uuid.UUID) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldAppID), v))
	})
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUserID), v))
	})
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldUserID), v))
	})
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.ApplicationUser {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ApplicationUser(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldUserID), v...))
	})
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.ApplicationUser {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ApplicationUser(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldUserID), v...))
	})
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v uuid.UUID) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldUserID), v))
	})
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v uuid.UUID) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldUserID), v))
	})
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v uuid.UUID) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldUserID), v))
	})
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v uuid.UUID) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldUserID), v))
	})
}

// OriginalEQ applies the EQ predicate on the "original" field.
func OriginalEQ(v bool) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldOriginal), v))
	})
}

// OriginalNEQ applies the NEQ predicate on the "original" field.
func OriginalNEQ(v bool) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldOriginal), v))
	})
}

// KycVerifyEQ applies the EQ predicate on the "kyc_verify" field.
func KycVerifyEQ(v bool) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldKycVerify), v))
	})
}

// KycVerifyNEQ applies the NEQ predicate on the "kyc_verify" field.
func KycVerifyNEQ(v bool) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldKycVerify), v))
	})
}

// GaVerifyEQ applies the EQ predicate on the "ga_verify" field.
func GaVerifyEQ(v bool) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldGaVerify), v))
	})
}

// GaVerifyNEQ applies the NEQ predicate on the "ga_verify" field.
func GaVerifyNEQ(v bool) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldGaVerify), v))
	})
}

// GaLoginEQ applies the EQ predicate on the "ga_login" field.
func GaLoginEQ(v bool) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldGaLogin), v))
	})
}

// GaLoginNEQ applies the NEQ predicate on the "ga_login" field.
func GaLoginNEQ(v bool) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldGaLogin), v))
	})
}

// SmsLoginEQ applies the EQ predicate on the "sms_login" field.
func SmsLoginEQ(v bool) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSmsLogin), v))
	})
}

// SmsLoginNEQ applies the NEQ predicate on the "sms_login" field.
func SmsLoginNEQ(v bool) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldSmsLogin), v))
	})
}

// LoginNumberEQ applies the EQ predicate on the "Login_number" field.
func LoginNumberEQ(v uint32) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldLoginNumber), v))
	})
}

// LoginNumberNEQ applies the NEQ predicate on the "Login_number" field.
func LoginNumberNEQ(v uint32) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldLoginNumber), v))
	})
}

// LoginNumberIn applies the In predicate on the "Login_number" field.
func LoginNumberIn(vs ...uint32) predicate.ApplicationUser {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ApplicationUser(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldLoginNumber), v...))
	})
}

// LoginNumberNotIn applies the NotIn predicate on the "Login_number" field.
func LoginNumberNotIn(vs ...uint32) predicate.ApplicationUser {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ApplicationUser(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldLoginNumber), v...))
	})
}

// LoginNumberGT applies the GT predicate on the "Login_number" field.
func LoginNumberGT(v uint32) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldLoginNumber), v))
	})
}

// LoginNumberGTE applies the GTE predicate on the "Login_number" field.
func LoginNumberGTE(v uint32) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldLoginNumber), v))
	})
}

// LoginNumberLT applies the LT predicate on the "Login_number" field.
func LoginNumberLT(v uint32) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldLoginNumber), v))
	})
}

// LoginNumberLTE applies the LTE predicate on the "Login_number" field.
func LoginNumberLTE(v uint32) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldLoginNumber), v))
	})
}

// CreateAtEQ applies the EQ predicate on the "create_at" field.
func CreateAtEQ(v uint32) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreateAt), v))
	})
}

// CreateAtNEQ applies the NEQ predicate on the "create_at" field.
func CreateAtNEQ(v uint32) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCreateAt), v))
	})
}

// CreateAtIn applies the In predicate on the "create_at" field.
func CreateAtIn(vs ...uint32) predicate.ApplicationUser {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ApplicationUser(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldCreateAt), v...))
	})
}

// CreateAtNotIn applies the NotIn predicate on the "create_at" field.
func CreateAtNotIn(vs ...uint32) predicate.ApplicationUser {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ApplicationUser(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldCreateAt), v...))
	})
}

// CreateAtGT applies the GT predicate on the "create_at" field.
func CreateAtGT(v uint32) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCreateAt), v))
	})
}

// CreateAtGTE applies the GTE predicate on the "create_at" field.
func CreateAtGTE(v uint32) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCreateAt), v))
	})
}

// CreateAtLT applies the LT predicate on the "create_at" field.
func CreateAtLT(v uint32) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCreateAt), v))
	})
}

// CreateAtLTE applies the LTE predicate on the "create_at" field.
func CreateAtLTE(v uint32) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCreateAt), v))
	})
}

// DeleteAtEQ applies the EQ predicate on the "delete_at" field.
func DeleteAtEQ(v uint32) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDeleteAt), v))
	})
}

// DeleteAtNEQ applies the NEQ predicate on the "delete_at" field.
func DeleteAtNEQ(v uint32) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldDeleteAt), v))
	})
}

// DeleteAtIn applies the In predicate on the "delete_at" field.
func DeleteAtIn(vs ...uint32) predicate.ApplicationUser {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ApplicationUser(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldDeleteAt), v...))
	})
}

// DeleteAtNotIn applies the NotIn predicate on the "delete_at" field.
func DeleteAtNotIn(vs ...uint32) predicate.ApplicationUser {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ApplicationUser(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldDeleteAt), v...))
	})
}

// DeleteAtGT applies the GT predicate on the "delete_at" field.
func DeleteAtGT(v uint32) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldDeleteAt), v))
	})
}

// DeleteAtGTE applies the GTE predicate on the "delete_at" field.
func DeleteAtGTE(v uint32) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldDeleteAt), v))
	})
}

// DeleteAtLT applies the LT predicate on the "delete_at" field.
func DeleteAtLT(v uint32) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldDeleteAt), v))
	})
}

// DeleteAtLTE applies the LTE predicate on the "delete_at" field.
func DeleteAtLTE(v uint32) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldDeleteAt), v))
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ApplicationUser) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ApplicationUser) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ApplicationUser) predicate.ApplicationUser {
	return predicate.ApplicationUser(func(s *sql.Selector) {
		p(s.Not())
	})
}
